### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by Abelon38** [alberto-acevedo/cesium-navigation#30] opened 2017-01-08 20:02 UTC
Hi there! 
I hope you qre doing greate guys! I am trying to install the Navegation plugin into my cesium 1.29 and I am getting the following error:
25951 error Windows_NT 10.0.10586
25952 error argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
25953 error node v7.4.0
25954 error npm  v4.0.5
25955 error code ELIFECYCLE
25956 error cesium-navigation@1.1.2 postinstall: `bower install`
25956 error Exit status 1
25957 error Failed at the cesium-navigation@1.1.2 postinstall script 'bower install'.
25957 error Make sure you have the latest version of node.js and npm installed.
25957 error If you do, this is most likely a problem with the cesium-navigation package,
25957 error not with npm itself.
25957 error Tell the author that this fails on your system:
25957 error     bower install
25957 error You can get information on how to open an issue for this project with:
25957 error     npm bugs cesium-navigation
25957 error Or if that isn't available, you can get their info via:
25957 error     npm owner ls cesium-navigation
25957 error There is likely additional logging output above.
25958 verbose exit [ 1, true ]

Does anyone knows what¨s gong on here?
Regards!
Abel

**Comment by Larcius** [comment] 2017-01-08 20:27
There is a problem with bower. Please run
`bower install`
and tell me the result.

**Comment by Abelon38** [comment] 2017-01-08 21:53
Hi Alberto!
Habla espanol?

Maybe is me that I am missing something, This is how i did: 1- Download and
saved the Navagation plugin in the "ThirdParty" catalog in Cesium, 2- with
cmd I get into the "ThirdParty" catalog and I run npm install, and then I
got the error.

I tried with "npm bower install" and I got the following:

C:\Users\abelg\Desktop\terria\Cesium129\ThirdParty\cesium-navigation>npm
bower install

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\abelg\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@4.0.5 C:\nodejs\node_modules\npm

C:\Users\abelg\Desktop\terria\Cesium129\ThirdParty\cesium-navigation>
Nothing happens ..

Thanks for your time!
Abel

2017-01-08 21:27 GMT+01:00 Gabriel Cordes <notifications@github.com>:

**Comment by Larcius** [comment] 2017-01-08 22:41
The package.json states that ```bower``` is needed and that as part of ```npm install``` the command ```bower install``` is called.
The error message you get when running ```npm install``` is caused by that command.
So in order to get more information what went wrong please run
`bower install`
in the console (without leading ```npm ```).

I noticed that in the ```package.json``` no version is given for ```bower``` so it might be an issue with a non-compatible recent version.
For me it works with bower version ```1.7.9``` so you can try to change line ```7``` of ```package.json```
from
`        "bower": "*"`
to
`        "bower": "1.7.9"`
and then rerun
`npm install`

**Comment by Larcius** [comment] 2017-01-08 22:53
And since you are using ```Windows``` please pay regard to
[https://www.npmjs.com/package/bower#windows-users](https://www.npmjs.com/package/bower#windows-users)

**Comment by Abelon38** [comment] 2017-01-09 18:24
Hi Gabriel!

Too bad I get the same error. I have even tried on a windows server 2012
and in my private datorn windows 10 and still the same. I also did the
changes on bower and even installed an older version av node.js and still
the same. Is there something else I should try?

Thanks for your time!
Abel

2017-01-08 23:53 GMT+01:00 Gabriel Cordes <notifications@github.com>:

**Comment by alberto-acevedo** [comment] 2017-01-09 18:53
Hola Abel,

I just tested in my Windows 7 computer and I have no issues. I always build the plugin outside of the ThirdParty folder.  Let's try the following:

remove the node_modules folder located at the root of the Cesium-navigation folder. Try again running npm install. If everything is fine you will see back the node_modules folder .

If the problem persists there must be modules installed as global that are causing the issue. Try removing the node_modules under User/<your name>/.... and then try again to run npm install. If you needed the modules as global you will have to install them again.

Let me know the outcome (Me dejas saber si el probema se resuelve).

Thanks,,

Alberto


-----Original Message-----

**Comment by Abelon38** [comment] 2017-01-09 19:26
Hi Gabriel!

thanks for your respond! I just tried for some minuts ago. I removed the
folder Node_Modules and then run npm install and the folder came back but
still getting the sema errors:
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. Med ensamrätt.

C:\Users\abelg>cd..

C:\Users>cd..

C:\>node -v
v7.4.0

C:\>npm -v
4.0.5

C:\>cd C:\Users\abelg\Desktop\terria\Cesium129\cesium-navigation

C:\Users\abelg\Desktop\terria\Cesium129\cesium-navigation>npm install
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN prefer global sqwish@0.2.2 should be installed with -g

> cesium-navigation@1.1.2 postinstall
C:\Users\abelg\Desktop\terria\Cesium129\cesium-navigation
> bower install

bower almond#^0.3.2             ENOGIT git is not installed or not in the
PATH

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\nodejs\\node.exe"
"C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! cesium-navigation@1.1.2 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cesium-navigation@1.1.2 postinstall script 'bower
install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the
cesium-navigation package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project
with:
npm ERR!     npm bugs cesium-navigation
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cesium-navigation
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
C:\Users\abelg\Desktop\terria\Cesium129\cesium-navigation\npm-debug.log

C:\Users\abelg\Desktop\terria\Cesium129\cesium-navigation>

2017-01-09 19:53 GMT+01:00 Alberto Acevedo <notifications@github.com>:

**Comment by Abelon38** [comment] 2017-01-16 13:45
Hi Gabriel!
Is that possible for you to contact me direct to my e-mail:
abel.gonzalez.c@gmail.com

Saludos!
Abel

2017-01-09 20:25 GMT+01:00 Abel Gonzalez <abel.gonzalez.c@gmail.com>:

**Comment by Larcius** [comment] 2017-01-17 17:43
Dear Abel,

Your log says:
```bower almond#^0.3.2             ENOGIT git is not installed or not in the PATH```
have you installed GIT? In order to use bower you need GIT. Please follow these instructions:
https://www.npmjs.com/package/bower#windows-users

Best regards,
Gabriel

**Comment by Abelon38** [comment] 2017-01-17 22:28
It worked!
I had to install GIT as you said!. Now is about some configuration only.
Thanks Gabriel for a great code and support!
Regards!
Abel

2017-01-17 18:43 GMT+01:00 Gabriel Cordes <notifications@github.com>:

**Comment by Larcius** [comment] 2017-01-20 11:19
Your're welcome, Abel

@alberto-acevedo Please close this issue

**Comment by alberto-acevedo** [comment] 2017-02-03 19:20
Closing issue.

**Closed** 2017-02-03 19:20 UTC
